version: '3.8'

services:
  blue:
    build: .
    container_name: blue_app
    environment:
      - FEATURE_NEW_API=false
      - APP_COLOR=BLUE
    ports:
      - "5000:5000"

  green:
    build: .
    container_name: green_app
    environment:
      - FEATURE_NEW_API=true
      - APP_COLOR=GREEN
    ports:
      - "5001:5000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - blue
      - green